[package]
name = "syncstream"
version = "0.1.0"
edition = "2024"
authors = ["Taxrosdev"]
rust-version = "1.85"
description = "Simple yet capable content-addressed storage, designed for package managers and immutable distros."
readme = "README.md"
repository = "https://github.com/Taxrosdev/SyncStream"
license = "MIT OR Apache-2.0"

[dependencies]
async-compression = { version = "^0.4", features = ["futures-io", "lz4", "xz", "zstd"] }
blake3 = "^1.8"
futures-core = "^0.3"
futures-util = { version = "^0.3", features = ["io"] }
reqwest = { version = "^0.13", features = ["stream"], optional = true }
serde = { version = "^1.0", features = ["derive"], optional = true }
thiserror = "^2"
tokio = { version = "^1.49", features = ["fs", "macros"], optional = true }
tokio-stream = { version = "^0.1", optional = true }
tokio-util = { version = "^0.7", optional = true }

[target.'cfg(unix)'.dependencies]
nix = { version = "^0.30", features = ["fs"] }

[features]
default = ["reqwest"]
reqwest = ["dep:reqwest"]
tokio = ["dep:tokio", "dep:tokio-stream", "dep:tokio-util", "async-compression/tokio"]
serde = ["dep:serde"]

[dev-dependencies]
httpmock = "^0.8"
temp-dir = "^0.1"
temp-file = "^0.1"
tokio = { version = "^1.49", features = ["fs", "macros", "rt-multi-thread"] }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
pedantic = "warn"

